# Generated by Django 4.2.7 on 2025-11-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='size',
            field=models.CharField(choices=[('small', 'Small (< 2 inches)'), ('medium', 'Medium (2-5 inches)'), ('large', 'Large (5-10 inches)'), ('xlarge', 'Extra Large (> 10 inches)')], default='medium', max_length=20),
        ),
    ]
