# Generated by Django 4.2.7 on 2025-11-08 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_fish_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='fishes/media/')),
                ('external_url', models.URLField(blank=True, help_text='Optional external video URL (e.g., YouTube)', null=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='store.fish')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
