# Generated by Django 4.2.7 on 2025-11-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_fishmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in inches', max_digits=6, null=True),
        ),
    ]
