# Generated by Django 4.2.7 on 2025-11-08 05:36

from django.db import migrations


def convert_size_to_numeric(apps, schema_editor):
    # Use raw SQL to update the data
    with schema_editor.connection.cursor() as cursor:
        # Set NULL for all existing records with string values
        cursor.execute("""
            UPDATE store_fish 
            SET size = NULL 
            WHERE size IS NOT NULL
        """)


def reverse_conversion(apps, schema_editor):
    # No need to reverse this
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_fish_size'),
    ]

    operations = [
        migrations.RunPython(convert_size_to_numeric, reverse_conversion),
    ]
