# Generated by Django 4.2.7 on 2025-11-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_payment_method_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.order'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'order')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='fish',
        ),
    ]
