# Generated by Django 4.2.7 on 2025-11-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If checked, this fish appears in Featured Fishes section'),
        ),
    ]
