# Generated by Django 4.2.7 on 2025-11-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_fish_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email_support', models.EmailField(blank=True, max_length=254)),
                ('email_sales', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +911234567890)', max_length=50)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed/share URL')),
                ('opening_hours', models.TextField(blank=True, help_text='One entry per line, e.g. Mon-Fri: 9:00 - 18:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
