# Generated by Django 4.2.7 on 2025-11-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_review_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='minimum_order_quantity',
            field=models.IntegerField(default=1, help_text='Minimum quantity required per order'),
        ),
    ]
