# Generated by Django 4.2.7 on 2025-11-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_fish_minimum_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
