# Generated by Django 4.2.7 on 2025-11-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_coupon_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='show_in_suggestions',
            field=models.BooleanField(default=True, help_text='Show this coupon in checkout suggestions'),
        ),
    ]
