# Generated by Django 4.2.7 on 2025-11-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_coupon_show_in_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('discount_text', models.CharField(help_text="Short highlight like 'Save 25%' or 'Flat ₹500 Off'", max_length=80)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
    ]
