# Generated by Django 4.2.7 on 2025-11-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_limitedoffer_alter_coupon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedoffer',
            name='bg_color',
            field=models.CharField(blank=True, help_text='Optional hex color (e.g. #1e90ff) used when no image', max_length=7),
        ),
        migrations.AddField(
            model_name='limitedoffer',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional banner image for the card background', null=True, upload_to='offers/'),
        ),
    ]
