# Generated by Django 4.2.7 on 2025-11-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_limitedoffer_bg_color_limitedoffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedoffer',
            name='fish',
            field=models.ForeignKey(blank=True, help_text='Optional: Select a fish to redirect users when they click the banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limited_offers', to='store.fish'),
        ),
    ]
