# Generated by Django 4.2.7 on 2025-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_accessory_orderaccessoryitem_accessorycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='minimum_order_quantity',
            field=models.IntegerField(default=1, help_text='Minimum quantity required per order'),
        ),
    ]
