# Generated by Django 4.2.7 on 2025-11-13 14:32

from django.db import migrations
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_accessory_minimum_order_quantity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', store.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
