# Generated by Django 4.2.7 on 2025-11-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_add_provider_order_id'),
        ('store', '0025_add_provider_order_id'),
    ]

    operations = [
    ]
