# Generated by Django 4.2.7 on 2026-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingChargeByLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='e.g., Kerala, Tamil Nadu, Delhi, Maharashtra, etc.', max_length=100, unique=True)),
                ('shipping_charge', models.DecimalField(decimal_places=2, help_text='Shipping charge for this location', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable shipping to this location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Charge by Location',
                'verbose_name_plural': 'Shipping Charges by Location',
                'ordering': ['location_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactgallerymedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
