# Generated by Django 4.2.7 on 2026-01-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_shippingchargebylocation_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='show_as_banner',
            field=models.BooleanField(default=False, help_text='When checked, show this accessory as a wide banner on the homepage'),
        ),
    ]
