# Generated by Django 4.2.7 on 2026-01-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_accessory_show_as_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='show_as_banner',
            field=models.BooleanField(default=False, help_text='Show this accessory as a homepage banner'),
        ),
    ]
