# Generated by Django 4.2.7 on 2025-12-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_combooffer_end_time_remove_combooffer_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='store.combooffer'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'fish', 'combo')},
        ),
    ]
