# Generated by Django 5.2.9 on 2025-12-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_cart_unique_together_cart_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combooffer',
            name='show_in_limited_offers',
            field=models.BooleanField(default=False, help_text='When enabled, this combo can appear in the Limited Offers section on the homepage'),
        ),
    ]
