# Generated by Django 5.2.9 on 2025-12-03 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_combooffer_show_in_limited_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedoffer',
            name='combo',
            field=models.ForeignKey(blank=True, help_text='Optional: Select a combo to redirect users when they click the banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limited_offers', to='store.combooffer'),
        ),
    ]
