# Generated by Django 4.2.7 on 2025-12-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_limitedoffer_combo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combooffer',
            name='show_in_limited_offers',
        ),
        migrations.RemoveField(
            model_name='limitedoffer',
            name='combo',
        ),
    ]
