# Generated by Django 4.2.7 on 2025-12-04 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_remove_combooffer_show_in_limited_offers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitedoffer',
            options={},
        ),
        migrations.RemoveField(
            model_name='limitedoffer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='limitedoffer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='limitedoffer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='limitedoffer',
            name='show_on_homepage',
        ),
        migrations.RemoveField(
            model_name='limitedoffer',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='limitedoffer',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='ComboDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Optional hero image to show for this combo on the homepage', null=True, upload_to='combo_displays/')),
                ('bg_color', models.CharField(blank=True, help_text='Optional fallback background color (hex)', max_length=32, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='store.combooffer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
