# Generated by Django 5.2.9 on 2025-12-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_limitedoffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combooffer',
            name='banner_image',
            field=models.ImageField(upload_to='combo_banners/', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='combooffer',
            name='show_as_banner',
            field=models.BooleanField(default=False),
        ),
    ]
