# Generated by Django 4.2.7 on 2025-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_limitedoffer_options_limitedoffer_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Accessory Category',
                'verbose_name_plural': 'Accessory Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='ComboCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Combo Offer Category',
                'verbose_name_plural': 'Combo Offer Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='FishCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Fish Category',
                'verbose_name_plural': 'Fish Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Plant Category',
                'verbose_name_plural': 'Plant Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('fish', 'Fish'), ('combo', 'Combo Offers'), ('accessory', 'Accessories'), ('plant', 'Plants')], default='fish', max_length=20),
        ),
    ]
