# Generated by Django 5.2.9 on 2025-12-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_accessorycategory_combocategory_fishcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combooffer',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional: select a combo category to organize this offer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_offers', to='store.category'),
        ),
    ]
