# Generated by Django 4.2.7 on 2025-12-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_combooffer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combooffer',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a combo offer category to help group related bundles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_offers', to='store.category'),
        ),
    ]
