# Generated by Django 4.2.7 on 2025-12-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_plant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plant',
            new_name='store_plant_is_acti_418d3a_idx',
            old_name='store_plant_active_order_idx',
        ),
    ]
