# Generated by Django 4.2.7 on 2025-12-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_orderplantitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants/gallery/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='store.plant')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
