# Generated by Django 4.2.7 on 2026-01-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_shippingchargesetting_unserviceable_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='excerpt',
            new_name='sub_title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
